#ifndef __INFINITY_INPUT__
#define __INFINITY_INPUT__

#include <glib.h>

typedef enum {
	INFINITY_KEY_RIGHT,
	INFINITY_KEY_LEFT,
	INFINITY_KEY_UP,
	INFINITY_KEY_DOWN,
	INFINITY_KEY_PREV,
	INFINITY_KEY_PLAY,
	INFINITY_KEY_PAUSE,
	INFINITY_KEY_STOP,
	INFINITY_KEY_NEXT,
	INFINITY_KEY_FULLSCREEN,
	INFINITY_KEY_EXIT_FULLSCREEN,
	INFINITY_KEY_NEXT_PALETTE,
	INFINITY_KEY_NEXT_EFFECT,
	INFINITY_KEY_TOGGLE_INTERACTIVE
} InfinityKey;

#ifdef __cplusplus
extern "C" {
#endif

void infinity_queue_key(InfinityKey key);

#ifdef __cplusplus
}
#endif

#endif /* __INFINITY_INPUT__ */
